// <auto-generated />
using System;
using DeviceManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeviceManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718034959_AddCreatedTimeToDevice")]
    partial class AddCreatedTimeToDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeviceManagement.Api.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            Name = "Desktop"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            Name = "Monitor"
                        });
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            CreatedAt = new DateTime(2026, 7, 18, 3, 49, 57, 960, DateTimeKind.Utc).AddTicks(3217),
                            EmployeeId = 1L,
                            IsDeleted = false,
                            Name = "Laptop1",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 7, 18, 3, 49, 57, 960, DateTimeKind.Utc).AddTicks(3367)
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            CreatedAt = new DateTime(2026, 7, 18, 3, 49, 57, 960, DateTimeKind.Utc).AddTicks(3647),
                            EmployeeId = 2L,
                            IsDeleted = false,
                            Name = "Desktop1",
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 7, 18, 3, 49, 57, 960, DateTimeKind.Utc).AddTicks(3647)
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 3L,
                            CreatedAt = new DateTime(2026, 7, 18, 3, 49, 57, 960, DateTimeKind.Utc).AddTicks(3649),
                            EmployeeId = 1L,
                            IsDeleted = false,
                            Name = "Monitor1",
                            Status = 3,
                            UpdatedAt = new DateTime(2026, 7, 18, 3, 49, 57, 960, DateTimeKind.Utc).AddTicks(3649)
                        });
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            Name = "Jason Yan"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            Name = "Freya Liu"
                        });
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$ogfduxgaoWgAXcmymvqCG.Xd3ud9PrXV.0eFiCMDuu2Kx25cnf/pu",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$ogfduxgaoWgAXcmymvqCG.Xd3ud9PrXV.0eFiCMDuu2Kx25cnf/pu",
                            Role = "User",
                            Username = "JasonYan"
                        });
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Device", b =>
                {
                    b.HasOne("DeviceManagement.Api.Models.Category", "Category")
                        .WithMany("Devices")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeviceManagement.Api.Models.Employee", "Employee")
                        .WithMany("Devices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Category", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Employee", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
