// <auto-generated />
using DeviceManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeviceManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709023139_AddUsers1")]
    partial class AddUsers1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeviceManagement.Api.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Desktop"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Monitor"
                        });
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CategoryId1")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId1");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            EmployeeId = 1L,
                            IsDeleted = false,
                            Name = "Laptop1",
                            Status = 0
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            EmployeeId = 2L,
                            IsDeleted = false,
                            Name = "Desktop1",
                            Status = 1
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 3L,
                            EmployeeId = 1L,
                            IsDeleted = false,
                            Name = "Monitor1",
                            Status = 3
                        });
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Jason Yan"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Freya Liu"
                        });
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123456",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "123456",
                            Role = "User",
                            Username = "JasonYan"
                        });
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Device", b =>
                {
                    b.HasOne("DeviceManagement.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceManagement.Api.Models.Category", null)
                        .WithMany("Devices")
                        .HasForeignKey("CategoryId1");

                    b.HasOne("DeviceManagement.Api.Models.Employee", "Employee")
                        .WithMany("Devices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Category", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("DeviceManagement.Api.Models.Employee", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
