name: DeviceManagement API CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore DeviceManagement.Api/DeviceManagement.Api.sln

      - name: Build
        run: dotnet build DeviceManagement.Api/DeviceManagement.Api.sln --no-restore

  smoke:

    needs: build

    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore DeviceManagement.Api/DeviceManagement.Api.sln

      - name: Run Smoke Tests
        run: >
          dotnet test DeviceManagement.Api/DeviceManagement.Api.sln
          --filter "Category=Smoke"

  regression:

    needs: build

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore DeviceManagement.Api/DeviceManagement.Api.sln

      - name: Run Regression Tests
        run: 
          dotnet test DeviceManagement.Api/DeviceManagement.Api.sln
          --filter "Category=Regression"
          --collect:"XPlat Code Coverage"