name: DeviceManagement API CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore DeviceManagement.Api/DeviceManagement.Api.sln

      - name: Build
        run: dotnet build DeviceManagement.Api/DeviceManagement.Api.sln --no-restore

  smoke:

    needs: build

    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore DeviceManagement.Api/DeviceManagement.Api.sln

      - name: Run Smoke Tests
        run: >
          dotnet test DeviceManagement.Api/DeviceManagement.Api.sln
          --filter "Category=Smoke"

  regression:

    needs: build

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore DeviceManagement.Api/DeviceManagement.Api.sln

      - name: Run Regression Tests With Coverage
        run: 
          dotnet test DeviceManagement.Api/DeviceManagement.Api.sln 
          --filter "Category=Regression"
          --collect:"XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool


      - name: Generate Coverage Report
        run: |
          reportgenerator \
          -reports:"**/coverage.cobertura.xml" \
          -targetdir:"coverage-report" \
          -reporttypes:Html \
          -historydir:coverage-history \
          -classfilters:"-DeviceManagement.Api.Migrations.*"


      - name: Upload Coverage Report
        uses: actions/upload-pages-artifact@v4
        with:
          path: coverage-report

  deploy:
    needs: regression
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Coverage Report
        id: deployment
        uses: actions/deploy-pages@v4