name: smoke test

pull_request:
    branches:
      - main

jobs:

  smoke test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'


    - name: Restore
      run: dotnet restore DeviceManagement.Api/DeviceManagement.Api.sln

    - name: Build
      run: dotnet build DeviceManagement.Api/DeviceManagement.Api.sln --no-restore

    - name: Run Smoke Tests
      run:
        dotnet test DeviceManagement.Api/DeviceManagement.Api.sln \
        --no-build \
        --filter "Category=Smoke"